'use strict';

export default {
    REQUEST_INSIGHTS: 'REQUEST_INSIGHTS',
    REQUEST_SERVICES: 'REQUEST_SERVICES',
    REQUEST_APPLICATION_ID: 'REQUEST_APPLICATION_ID',
    REQUEST_APPLICATIONS: 'REQUEST_APPLICATIONS',
    REQUEST_INSIGHT_ID: 'REQUEST_INSIGHT_ID',
    /**
     * Build all data to be displayed in home
     * page.
     */
    REQUEST_COMPILE_DATA: 'REQUEST_COMPILE_DATA',

    NAVIGATION_GOTO: 'NAVIGATION_GOTO',

    APPLICATION_NEW: 'APPLICATION_NEW',
    APPLICATION_VIEW: 'APPLICATION_VIEW',
    APPLICATION_EDIT: 'APPLICATION_EDIT'
};
