'use strict';

export default {
    REQUEST_INSIGHTS: 'REQUEST_INSIGHTS',
    REQUEST_SERVICES: 'REQUEST_SERVICES',
    REQUEST_APPLICATION_ID: 'REQUEST_APPLICATION_ID',
    REQUEST_APPLICATIONS: 'REQUEST_APPLICATIONS',
    REQUEST_INSIGHT_ID: 'REQUEST_INSIGHT_ID',
    /**
     * Build all data to be displayed in home
     * page.
     */
    REQUEST_COMPILE_DATA: 'REQUEST_COMPILE_DATA',

    NAVIGATION_GOTO: 'NAVIGATION_GOTO',
    NAVIGATION_GO_BACK: 'NAVIGATION_GO_BACK',
    NAVIGATION_GO_FORWARD: 'NAVIGATION_GO_FORWARD',

    APPLICATION_VIEW: 'APPLICATION_VIEW',

    APPLICATION_NEW: 'APPLICATION_NEW',
    APPLICATION_CREATE: 'APPLICATION_CREATE',

    APPLICATION_EDIT: 'APPLICATION_EDIT',
    APPLICATION_UPDATE: 'APPLICATION_UPDATE',

    APPLICATION_DELETE: 'APPLICATION_DELETE',
    APPLICATION_PAUSE: 'APPLICATION_PAUSE',
};
